-- clear cache

require('plenary.reload').reload_module('configs/bufferline')
-- require('plenary.reload').reload_module('configs/diffview')
require('plenary.reload').reload_module('configs/evilline')
require('plenary.reload').reload_module('configs/flutter-tools')
require('plenary.reload').reload_module('configs/gitsigns-nvim')
require('plenary.reload').reload_module('configs/lsp-ts-utils')
-- require('plenary.reload').reload_module('configs/neogit')
require('plenary.reload').reload_module('configs/lua-dev-nvim')
require('plenary.reload').reload_module('configs/nvim-compe')
require('plenary.reload').reload_module('configs/nvim-lspconfig')
require('plenary.reload').reload_module('configs/nvim-tree')
require('plenary.reload').reload_module('configs/nvim-treesitter')
require('plenary.reload').reload_module('configs/telescope')
-- require('plenary.reload').reload_module('configs/vgit')
require('plenary.reload').reload_module('configs/which-key')

-- reload

require('configs/bufferline')
-- require('configs/diffview')
require('configs/evilline')
require('configs/flutter-tools')
require('configs/gitsigns-nvim')
require('configs/lsp-ts-utils')
-- require('configs/neogit')
require('configs/lua-dev-nvim')
require('configs/nvim-compe')
require('configs/nvim-lspconfig')
require('configs/nvim-tree')
require('configs/nvim-treesitter')
require('configs/telescope')
-- require('configs/vgit')
require('configs/which-key')
