-- clear cache

require('plenary.reload').reload_module('configs/bufferline-nvim')
require('plenary.reload').reload_module('configs/feline')
require('plenary.reload').reload_module('configs/flutter-tools-custom-telescope-menu')
require('plenary.reload').reload_module('configs/flutter-tools')
require('plenary.reload').reload_module('configs/gitsigns-nvim')
require('plenary.reload').reload_module('configs/lsp-ts-utils')
require('plenary.reload').reload_module('configs/lua-dev-nvim')
require('plenary.reload').reload_module('configs/nightfox-nvim')
require('plenary.reload').reload_module('configs/nvim-cmp')
require('plenary.reload').reload_module('configs/nvim-lspconfig')
require('plenary.reload').reload_module('configs/nvim-tree')
require('plenary.reload').reload_module('configs/nvim-treesitter')
require('plenary.reload').reload_module('configs/telescope')
require('plenary.reload').reload_module('configs/trouble-nvim')
require('plenary.reload').reload_module('configs/which-key')

-- reload

require('configs/bufferline-nvim')
require('configs/feline')
require('configs/flutter-tools-custom-telescope-menu')
require('configs/flutter-tools')
require('configs/gitsigns-nvim')
require('configs/lsp-ts-utils')
require('configs/lua-dev-nvim')
require('configs/nightfox-nvim')
require('configs/nvim-cmp')
require('configs/nvim-lspconfig')
require('configs/nvim-tree')
require('configs/nvim-treesitter')
require('configs/telescope')
require('configs/trouble-nvim')
require('configs/which-key')
